/**
 *      SONG:
 *          PLAY piano NOTES c,d,e,f
 *          PLAY guitar NOTES f,e,d,c
 */


Note          ::=   c | d | e | f | g | a | b

Notes         ::=   Note
              |     Notes,Notes

Instrument    ::=   Piano
              |     Guitar
              |     Marimba
              |     Trumpet

PlayCommand   ::=   PLAY Instrument

NoteCommand   ::=   NOTES Notes

Line          ::=   PlayCommand NoteCommand

Program       ::=   Line
              |     Line Program

Song          ::=   SONG: Program